### ISSUE TITLE
Can't get examples/iso2.py to work

### ISSUE THREAD

**Issue by bwrsandman** [rocky/pycdio#1]
I'm trying to prototype extracting files from a cue/bin disk image.
The `iso2.py` example mentions being able to extract  from cue/bin pairs but when running it, I can't seem to have it work as expected.
```
$ hostnamectl
  Operating System: Arch Linux
            Kernel: Linux 5.10.13-arch1-2
      Architecture: x86-64

$ pacman -Q python-pycdio libcdio
python-pycdio 2.1.0-5
libcdio 2.1.0-2

$ python --version               
Python 3.9.1

$ python iso2.py # commit sha 77dad0e040789a4b5e0b7c9bf913dc59f3f6043f
Could not get ISO-9660 file information for file copying in ../data/isofs-m1.cue
```

**Comment by rocky** [comment]
Is "../data/isofs-m1.cue" around ?

**Comment by bwrsandman** [comment]
Yes. I am running from examples/
```
$ ls "../data/isofs-m1.cue"
../data/isofs-m1.cue
```

**Comment by rocky** [comment]
Hmm. I get about the same thing. In fact, I am getting a Python error (on Python 3) when I try to build this. On Python2, I get what you have. 

Unfortunately (but not surprising and most likely) the error seems to be coming from a SWIG-generated shared object. 

I'll look at this at some point in the vague future, but it might be a long while. 

Very few people seem to be interested in this anymore. (Compare this project's ratings with my other projects). 

Hey, in the year and 1/2 that this has been on github. This is the first issue ever logged - Congratulations! 

If you are up for it to fix, go for it!
